apiVersion: apps/v1
kind: Deployment
metadata:
  name: aam-deployment
  labels:
    app: portfolio
spec:
  replicas: 2
  selector:
    matchLabels:
      app: portfolio
  template:
    metadata:
      labels:
        app: portfolio
    spec:
      containers:
      - name: portfolio-container
        image: aamdsam/devops-testing:latest
        ports:
        - containerPort: 80
        - containerPort: 443
---
apiVersion: v1
kind: Service
metadata:
  name: aam-service
  labels:
    app: portfolio
spec:
  type: ClusterIP
  selector:
    app: portfolio
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
  - protocol: TCP
    port: 443
    targetPort: 443

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: aam-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    cert-manager.io/cluster-issuer: "letsencrypt-prod" 
spec:
  rules:
  - host: devops-aam.dsam.web.id
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: aam-service
            port:
              number: 80
  # tls: 
  # - hosts:
  #   - portfolio-aam.dsam.web.id
  #   secretName: portfolio-tls
