apiVersion: apps/v1
kind: Deployment
metadata:
  name: helloworld-app
  labels:
    app: helloworld
spec:
  replicas: 2
  selector:
    matchLabels:
      app: helloworld
  template:
    metadata:
      labels:
        app: helloworld
    spec:
      containers:
      - name: helloworld-container
        image: redheaven/hello-world:latest
        ports:
        - containerPort: 8081
        envFrom:
        - configMapRef:
            name: application-properties
        volumeMounts:
        - name: config-volume
          mountPath: /app/resources
      volumes:
      - name: config-volume
        configMap:
          name: application-properties
---
apiVersion: v1
kind: Service
metadata:
  name: helloworld-service
spec:
  selector:
    app: helloworld
  ports:
    - protocol: TCP
      port: 8081
      targetPort: 8081
  type: NodePort

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: application-properties
data:
  application.properties: |
    server.port=8081
